export const SET_TOKEN = 'SET_TOKEN'

export const SET_COLLECTIONS = 'SET_COLLECTIONS'

export const SET_CIRCLES = 'SET_CIRCLES'

export const SET_QUESTIONS = 'SET_QUESTIONS'

export const SET_ATTENTIONS = 'SET_ATTENTIONS'

export const SET_ANSWERS = 'SET_ANSWERS'

export const SET_FOLLOWINGS = 'SET_FOLLOWINGS'

export const SET_FOLLOWERS = 'SET_FOLLOWERS'

export const SET_TAGS = 'SET_TAGS'
